name: infinite_scroll_chat
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  cached_network_image:
  cloud_firestore: ^4.2.0
  cloud_functions: ^4.0.6
  cupertino_icons:
  firebase_auth: ^4.2.0
  firebase_core: ^2.4.0
  flutter:
    sdk: flutter
  flutter_hooks:
  flutter_localizations:
    sdk: flutter
  flutter_spinkit:
  font_awesome_flutter:
  freezed_annotation:
  gap:
  hooks_riverpod:
  intl:
  json_annotation:
  path_to_regexp: 
  shimmer: 
  simple_logger: 
  tuple:
  uuid:

dev_dependencies:
  build_runner:
  fake_cloud_firestore: 
  flutter_launcher_icons:
  flutter_lints:
  flutter_test:
    sdk: flutter
  freezed:
  json_serializable:
  pedantic_mono:

flutter:
  uses-material-design: true

